# action.yml
name: Hello World
description: Greet someone and record the time
inputs:
  OPENSHIFT_AUTH_TOKEN_TEST:  # id of input
    description: OpenShift service account token
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.OPENSHIFT_AUTH_TOKEN_TEST }}
