# action.yml
name: Hello World
description: Greet someone and record the time
inputs:
  OPENSHIFT_AUTH_TOKEN_TEST:
    description: OpenShift service account token
    required: true
  NAMESPACE:
    description: OpenShift project namespace
    required: true
  APP_NAME:
    description: OpenShift app name label
    required: true
runs:
  using: docker
  image: Dockerfile
  env:
    NAMESPACE: ${{ inputs.NAMESPACE }}
    APP_NAME: ${{ inputs.APP_NAME }}
  args:
    - ${{ inputs.OPENSHIFT_AUTH_TOKEN_TEST }}
